#!/bin/bash
if [ "$1" = "help" ]
then 
    echo This is a bash script to execute test for project 0x0B-malloc_free
    echo To execute the first test run
    echo ./run testone
    echo There are 6 test cases to run all tests use
    echo ./run runall

elif [ "$1" = "testsix" ]
then 
    # gcc -o test main.c tests.c 0-create_array.c 1-strdup.c 2-str_concat.c 3-alloc_grid.c 4-free_grid.c
    echo Test six
elif [ "$1" = "deploy" ]
then 
    git add . 
    git commit -m $2
    git push origin master
    echo Code published to git
    
else 
    gcc -o test main.c tests.c 0-create_array.c 1-strdup.c 2-str_concat.c 3-alloc_grid.c 4-free_grid.c
    for arg in "$@"
    do 
        if [ "$arg" = "testfive" ]
        then
            ./test $arg
            leaks -atExit -- ./test
        else
            ./test $arg
        fi 
        
    done
fi

