#!/bin/bash
echo "Building projects ...OK"
gcc -Wall -pedantic -Werror -Wextra -std=gnu89 -o test main.c putchar.c 0-memset.c 1-memcpy.c 2-strchr.c 3-strspn.c 4-strpbrk.c 5-strstr.c 7-print_chessboard.c 8-print_diagsums.c

echo "Build Successful ...OK"
echo "Executing Tests..."
./test
echo "Done...OK"
